FROM openjdk:17
COPY build/libs/Equus-Config-Server-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]

FROM nginx
COPY nginx.conf /etc/nginx/conf.d/nginx.conf

ARG CONFIG_URI
ENV CONFIG_URI ${CONFIG_URI}

ARG CONFIG_USERNAME
ENV CONFIG_USERNAME ${CONFIG_USERNAME}

ARG CONFIG_PASSWORD
ENV CONFIG_PASSWORD ${CONFIG_PASSWORD}

