spring:
  application:
    name: Entry-Config-Server
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URI}
          username: ${CONFIG_USERNAME}
          password: ${CONFIG_PASSWORD}
          ignore-local-ssh-settings: true
          search-paths: config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

server:
  port: 8888