spring:
  application:
    name: Entry-Config-Server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URI}
          username: ${CONFIG_USERNAME}
          password: ${CONFIG_PASSWORD}
          ignore-local-ssh-settings: true
          search-paths: config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh


server:
  port: 8888
  servlet:
    context-path: /equus-config
